### ISSUE TITLE
base::func

### ISSUE THREAD

**Issue by Reckziegel** [luketesser/vol_surf#1]
Nas funções do pacote `base` não é necessário usar `pacote::função`, mas nada impede também.

https://github.com/luketesser/vol_surf/blob/18db292ce7f72986444cc416200d027250da2ba3/R/vol_coef.R#L16

**Comment by luketesser** [comment]
Eu coloquei assim para evitar conflito com funções de outros pacotes que tem o mesmo nome caso estejam carregados.
